name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via bastion
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "${{ secrets.EC2_KEY }}" > key.pem
            chmod 400 key.pem

            ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.PRIVATE_IP_1 }} 'bash ~/aws-webapp-pvt-ec2/deploy.sh'
            ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.PRIVATE_IP_2 }} 'bash ~/aws-webapp-pvt-ec2/deploy.sh'
